Add Simplestyle doc
geolonia/docs.geolonia.com pull request #47
Opened 2022-09-30 03:49 UTC by kamataryo

2022-09-30 03:57 UTC, keichan34 requested changes

2022-09-30 03:57 UTC, keichan34 commented on javascript-api/index.md
> +## Symplestyle を JavaScript で扱う
`symplestyle` -> `simplestyle`
`fitBound` -> `fitBounds`

2022-09-30 04:09 UTC, kamataryo commented on javascript-api/index.md
> +## Symplestyle を JavaScript で扱う
ありがとうございます 🙇

2022-10-03 01:23 UTC, kamataryo commented on javascript-api/index.md
> +  new geolonia.SimpleStyle(geojson)
https://github.com/geolonia/embed/pull/305 に合わせて修正

2022-10-03 03:47 UTC, keichan34 approved these changes

2022-10-03 05:22 UTC, naogify approved these changes
ありがとうございます！

2022-10-03 05:22 UTC, merged